// Replace this with the URL generated by the deploy_backend.ps1 script
const API_URL = "https://wyu6pvohvbz5xg5lwdmikl2dtu0gheoa.lambda-url.ap-south-1.on.aws/";

const promptInput = document.getElementById('prompt-input');
const submitBtn = document.getElementById('submit-btn');
const inputWrapper = document.getElementById('input-wrapper');
const loadingDiv = document.getElementById('loading');
const chatHistory = document.getElementById('chat-history');
const mainContainer = document.getElementById('main-container');

// Auto-resize textarea
promptInput.addEventListener('input', function() {
    this.style.height = 'auto';
    this.style.height = (this.scrollHeight) + 'px';
});

// Handle enter key to submit
promptInput.addEventListener('keydown', function(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        submitQuestion();
    }
});

submitBtn.addEventListener('click', submitQuestion);

function scrollToBottom(force = false) {
    if (!chatHistory) return;
    
    // Check how far we are from the bottom
    const distanceToBottom = chatHistory.scrollHeight - chatHistory.scrollTop - chatHistory.clientHeight;
    
    // If forced, or if we are already at the bottom (within a 50px threshold)
    if (force || distanceToBottom < 50) {
        chatHistory.scrollTop = chatHistory.scrollHeight;
    }
}

async function submitQuestion() {
    const question = promptInput.value.trim();
    if (!question) return;

    // Transition container on first question
    if (!mainContainer.classList.contains('answered')) {
        mainContainer.classList.add('answered');
    }

    // Add user question to UI
    const pairDiv = document.createElement('div');
    pairDiv.className = 'message-pair';
    
    const userDiv = document.createElement('div');
    userDiv.className = 'user-question';
    userDiv.textContent = `> ${question}`;
    
    pairDiv.appendChild(userDiv);
    chatHistory.appendChild(pairDiv);
    
    // Clear input and disable
    promptInput.value = '';
    promptInput.style.height = 'auto';
    promptInput.disabled = true;
    submitBtn.disabled = true;
    
    scrollToBottom(true);

    // Move loading indicator to the bottom of the chat history
    chatHistory.appendChild(loadingDiv);
    loadingDiv.classList.remove('hidden');
    scrollToBottom(true);

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ prompt: question })
        });

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        
        loadingDiv.classList.add('hidden');

        const oracleDiv = document.createElement('div');
        oracleDiv.className = 'oracle-answer';
        pairDiv.appendChild(oracleDiv);
        
        // Typewriter effect for parsed markdown answer
        const rawText = data.response || "The oracle is silent.";
        const parsedHTML = marked.parse(rawText);
        typeWriterHTML(parsedHTML, oracleDiv);

    } catch (error) {
        loadingDiv.classList.add('hidden');
        
        const oracleDiv = document.createElement('div');
        oracleDiv.className = 'oracle-answer';
        oracleDiv.style.color = "#ff4444";
        oracleDiv.textContent = `[ERROR] Connection to the void severed. Details: ${error.message}`;
        pairDiv.appendChild(oracleDiv);
        scrollToBottom(true);
        
        promptInput.disabled = false;
        submitBtn.disabled = false;
        promptInput.focus();
    }
}

function typeWriterHTML(html, element, speed = 10) {
    element.innerHTML = '';
    let i = 0;
    let isTag = false;
    let isEntity = false;
    let currentHTML = '';
    
    function type() {
        if (i < html.length) {
            let char = html.charAt(i);
            currentHTML += char;
            
            if (char === '<') isTag = true;
            if (char === '>') isTag = false;
            
            if (char === '&' && !isTag) isEntity = true;
            if (char === ';' && isEntity) isEntity = false;

            if (isTag || isEntity) {
                i++;
                type(); // Skip delay for tags and entities
            } else {
                element.innerHTML = currentHTML;
                scrollToBottom();
                i++;
                setTimeout(type, speed);
            }
        } else {
            promptInput.disabled = false;
            submitBtn.disabled = false;
            promptInput.focus();
        }
    }
    
    type();
}
